language: node_js
node_js:
  - "10"
services:
  - docker
before_install:
  - docker build -t athena .

deploy:
  provider: script
  script: docker push athena:latest
  on:
    branch: master
cache:
  directories:
    - "node_modules"
